<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RootNamespace>RagQuickstart</RootNamespace>
    <AssemblyName>RagQuickstart</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../../../tessera-dotnet/src/Tessera.Client/Tessera.Client.csproj" />
  </ItemGroup>

</Project>
